### ISSUE TITLE
(Т) Неправильная работа метода Car.ChangeOwner

### ISSUE THREAD

**Issue by ikit-mita** [NShilonosova/HomeWork2#1]
По твоей логике выходит, что даже если у водителя нету нужной категории, то все равно он будет прописан в паспорте машины

**Comment by NShilonosova** [comment]
Нет, не будет прописан. Наличие нужной категории проверяется в методе Driver.OwnCar

**Comment by ikit-mita** [comment]
@NShilonosova,
public void ChangeOwner(Driver newOwner, string newCarNumber)
        {
            CarPassport.Owner = newOwner;
            newOwner.OwnCar(this);
            CarNumber = newCarNumber;
        }

Но CarPassport.Owner выставляется перед тем, как проверка сработает

**Comment by NShilonosova** [comment]
Исправлено
